### ISSUE TITLE
Packet corruption issues

### ISSUE THREAD

**Issue by aardvarkk** [larku/RakNet#31]
I'm still getting packet corruption issues in the latest release of this code. I'm not overly familiar with the RakNet internals so I'm having trouble debugging, but it still looks related to this split packet issue that is supposed to be solved. When I run my app about 1/4 times a big message that I send (> MTU, I believe) is not received properly on the client side. The message ID is completely wrong and all of the data is mangled. Are there any tips about how best to see if this packet reordering is the issue? I'm currently running the PacketLogger but it doesn't show much that seems to help.

**Comment by aardvarkk** [comment]
I'm not entirely sure what's going on, but it seems the problem shows itself if I link my code against an archive built from CMake. If I build the .cpp files for RakNet directly in XCode and don't link against the archived library the problem doesn't seem to appear. Or at least with no detectable frequency.

**Comment by Kiddinglife** [comment]
Hi man. Oculus is now quite busy with doing VR and so they do not have time to update this project. 
The problem you said have been resolved in the community version raknet. see this repo [https://github.com/larku/RakNet](url)

**Comment by larku** [comment]
Note, there's a few other fixes provided by other users (in other Issues) that I'll be folding in to that fork over the next two weeks - so keep your eye out for some updates.
